# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:           Tayfun Cetiner
logo:             /assets/demo1.jpg
tagline:          'Ozgecmis'
description:      ''
email:            tyfn.cetiner@windowslive.com
phone:            +905445487924
url:              https:/tayfuncetiner.github.io
lomography:       https://www.lomography.com/homes/renitec/
baseurl:          #/ozgecmis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
plugins:
  - jekyll-paginate
  - jekyll-gist
  
